### PR TITLE
Cleanup the command line interface

### PR DESCRIPTION
**Pull request by neonichu**
- Use CLAide instead of escort as CLI parser gem
- Removed intermediary JSON conversion steps
- Implicitly validate JSON schema of input files instead of explicit command
- Cleaned up configuration by offering all options as CLI switches and options in the configuration file
- Offer aggregate import/publish actions

### CODE REVIEW

**Comment by neonichu** [comment]
We should probably first do a release with the better logging from #16 before merging this, as this is quite a huge chunk of stuff to review.

**Comment by neonichu** [comment]
Currently, all actions accept all CLI options, no matter if they are actually used or not. Not sure if that is a good thing  ¯\_(ツ)_/¯

**Comment by pxlpnk** [comment]
In general I think that a an option that is not needed in a context should
result in a usage error instead of being silently ignored.

**Comment by neonichu** [comment]
Makes sense, I have split up the options now. 

A problem are the aggregate commands like `import`, it will offer the `--threads` option, but it will only be applied to the `import-entries` action, as `import-content-model` and `import-assets` don't offer them.

**Comment by pxlpnk** [comment]
Looking good.

**Pull request merged**
