### PR TITLE
Fix webmock dependency, update http.rb to v0.9.0

### PR DESCRIPTION
**Pull request by neonichu**
We use http 0.8 and that is incompatible with previous versions of webmock.

### CODE REVIEW

**Comment by neonichu** [comment]
Seems like the tests are incompatible with the newer webmock, though  ¯\\\_(ツ)\_/¯

**Comment by pxlpnk** [comment]
Is there somehow a way of making this work?

**Comment by neonichu** [comment]
@pxlpnk that's the plan, I mainly created the PR to double-check that it is not an issue with my environment.

**Comment by pxlpnk** [comment]
:+1:

On 7/23/15, Boris Bügling <notifications@github.com> wrote:
> @pxlpnk that's the plan, I mainly created the PR to double-check that it is
> not an issue with my environment.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/contentful/contentful-importer.rb/pull/21#issuecomment-124063104


-- 
Andreas Tiefenthaler
Software Engineer
www.contentful.com

**Comment by neonichu** [comment]
Seems like bumping http fixed this ¯\\\_:computer:\_/¯

**Comment by pxlpnk** [comment]
Such computers. We might want to bump the http version in the other gems too then.

**Pull request merged**
